networks:
  network1:
    driver: bridge
    ipam:
      config:
      - subnet: 172.29.0.0/24
    name: network1
services:
  central-server:
    build: ./server
    networks:
      network1:
        ipv4_address: 172.29.0.2
    ports:
    - 5000:5000
  hmi1:
    build: ./hmi
    cap_add:
    - NET_ADMIN
    command: sh -c "apt-get update && apt-get install -y iproute2 && ip route del
      172.29.0.0/24 && ip route del default && ip route add 172.29.0.8 dev eth0 &&ip
      route add 172.29.0.0/24 via 172.29.0.8 && tail -f /dev/null"
    container_name: hmi1
    networks:
      network1:
        ipv4_address: 172.29.0.5
    tty: true
    volumes:
    - ./hmi/scripts:/scripts
  hmi2:
    build: ./hmi
    cap_add:
    - NET_ADMIN
    command: sh -c "apt-get update && apt-get install -y iproute2 && ip route del
      172.29.0.0/24 && ip route del default && ip route add 172.29.0.9 dev eth0 &&ip
      route add 172.29.0.0/24 via 172.29.0.9 && tail -f /dev/null"
    container_name: hmi2
    networks:
      network1:
        ipv4_address: 172.29.0.6
    tty: true
    volumes:
    - ./hmi/scripts:/scripts
  hmi_proxy1:
    build: ./proxy
    cap_add:
    - NET_ADMIN
    command: sh -c "apt-get update && apt-get install -y iproute2 && ip route add
      172.29.0.51 via 172.29.0.101 && ip route add 172.29.0.52 via 172.29.0.102 &&
      ip route add 172.29.0.6 via 172.29.0.9 && cd scripts && pip install ./python-netfilterqueue
      &&tail -f /dev/null"
    container_name: hmi_proxy1
    environment:
      DEVICE_IP: 172.29.0.5
    networks:
      network1:
        ipv4_address: 172.29.0.8
    tty: true
    volumes:
    - ./volumes/hmi_proxy1:/scripts
  hmi_proxy2:
    build: ./proxy
    cap_add:
    - NET_ADMIN
    command: sh -c "apt-get update && apt-get install -y iproute2 && ip route add
      172.29.0.51 via 172.29.0.101 && ip route add 172.29.0.52 via 172.29.0.102 &&
      ip route add 172.29.0.5 via 172.29.0.8 && cd scripts && pip install ./python-netfilterqueue
      &&tail -f /dev/null"
    container_name: hmi_proxy2
    environment:
      DEVICE_IP: 172.29.0.6
    networks:
      network1:
        ipv4_address: 172.29.0.9
    tty: true
    volumes:
    - ./volumes/hmi_proxy2:/scripts
  plc1:
    build: ./plc/plc1
    cap_add:
    - NET_ADMIN
    container_name: plc1
    networks:
      network1:
        ipv4_address: 172.29.0.51
    ports:
    - 8081:8080
  plc2:
    build: ./plc/plc1
    cap_add:
    - NET_ADMIN
    container_name: plc2
    networks:
      network1:
        ipv4_address: 172.29.0.52
    ports:
    - 8082:8080
  plc_proxy1:
    build: ./proxy
    cap_add:
    - NET_ADMIN
    command: sh -c "apt-get update && apt-get install -y iproute2 && ip route add
      172.29.0.52 via 172.29.0.102 && ip route add 172.29.0.5 via 172.29.0.8 && ip
      route add 172.29.0.6 via 172.29.0.9 && cd scripts && pip install ./python-netfilterqueue
      &&tail -f /dev/null"
    container_name: plc_proxy1
    environment:
      DEVICE_IP: 172.29.0.51
    networks:
      network1:
        ipv4_address: 172.29.0.101
    tty: true
    volumes:
    - ./volumes/plc_proxy1:/scripts
  plc_proxy2:
    build: ./proxy
    cap_add:
    - NET_ADMIN
    command: sh -c "apt-get update && apt-get install -y iproute2 && ip route add
      172.29.0.51 via 172.29.0.101 && ip route add 172.29.0.5 via 172.29.0.8 && ip
      route add 172.29.0.6 via 172.29.0.9 && cd scripts && pip install ./python-netfilterqueue
      &&tail -f /dev/null"
    container_name: plc_proxy2
    environment:
      DEVICE_IP: 172.29.0.52
    networks:
      network1:
        ipv4_address: 172.29.0.102
    tty: true
    volumes:
    - ./volumes/plc_proxy2:/scripts
version: '3.9'
